[tool.black]
line-length = 88

[tool.isort]
profile = "google"

[tool.interrogate]
fail-under = 100
ignore-module = true
ignore-nested-functions = true
ignore-semiprivate = true
exclude = [".vscode", "setup.py"]
color = true
verbose = 1

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:distutils Version classes are deprecated:DeprecationWarning",  # numpy 1.20 (python39-pandas12 env)
    "ignore:datetime.datetime.utcnow:DeprecationWarning",  # botocore python >= 3.12
]